# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
#  ⚙️ ENHANCED RUN ONE AT TIME - CONFIGURATION FILE
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
#  🔧 CORE PROCESSING SETTINGS
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

processing:
  # Maximum number of retry attempts for failed processes
  max_retries: 3

  # Delay between process executions (seconds)
  process_delay: 2

  # Timeout for individual process execution (seconds)
  process_timeout: 300

  # Maximum parallel processes (for future parallel implementation)
  max_parallel_processes: 1

  # Enable automatic recovery from interrupted sessions
  auto_recovery_enabled: true

  # Supported file extensions for process discovery
  supported_extensions:
    - ".md"
    - ".txt"
    - ".pdf"


# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
#  🔄 RETRY & BACKOFF STRATEGY
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

retry:
  # Retry strategy: "fixed", "exponential", "linear"
  strategy: "exponential"

  # Base delay for retry attempts (seconds)
  base_delay: 5

  # Maximum delay between retry attempts (seconds)
  max_delay: 300

  # Exponential backoff multiplier
  backoff_multiplier: 2.0

  # Add random jitter to retry delays (0.0-1.0)
  jitter_factor: 0.1

  # Retry specific error types
  retry_on_errors:
    - "selenium"
    - "timeout"
    - "connection"
    - "webdriver"


# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
#  📊 LOGGING & MONITORING
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

logging:
  # Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"

  # Enable console logging
  console_enabled: true

  # Enable file logging
  file_enabled: true

  # Log file path and rotation
  log_file: "Logs/enhanced_processor.log"
  max_log_size_mb: 50
  backup_count: 5

  # Log format
  format: "[%(asctime)s] %(levelname)s - %(name)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"

  # Enable performance monitoring
  performance_monitoring: true

  # Log subprocess output
  log_subprocess_output: true


# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
#  📁 DIRECTORY STRUCTURE
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
# NOTA: As pastas devem ser criadas manualmente. Não há mais criação automática.

directories:
  # Base directories for processing (must exist)
  reports_dir: "Reports"
  temp_dir: "Temp"
  logs_dir: "Logs"

  # Processing status directories (must exist in respective parent directories)
  processed_dir: "Reports/Processed"
  failed_dir: "Reports/Failed"
  pending_dir: "Reports/Pending"
  backup_dir: "Reports/Backup"

  # Directory creation has been removed (auto_create_dirs: false)
  auto_create_dirs: false

  # Backup original files before processing
  backup_originals: true


# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
#  🧹 RESOURCE MANAGEMENT & CLEANUP
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

cleanup:
  # Automatically cleanup temporary files
  auto_cleanup_temp: true

  # Cleanup temp files older than X hours
  temp_file_max_age_hours: 24

  # Maximum number of temporary script files to keep
  max_temp_scripts: 100

  # Cleanup old log files
  cleanup_old_logs: true

  # Keep log files for X days
  log_retention_days: 30


# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
#  🔐 SELENIUM & BROWSER SETTINGS
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

selenium:
  # WebDriver timeout settings
  implicit_wait: 10
  page_load_timeout: 30
  script_timeout: 30

  # Chrome browser options
  chrome_options:
    headless: false
    disable_gpu: false
    no_sandbox: true
    disable_dev_shm_usage: true

  # Window size for consistency
  window_size:
    width: 1920
    height: 1080


# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
#  🧠 AI MODEL CONFIGURATION
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

ai_models:
  # Default model for template generation
  default_template_model: "gpt-4o-mini"

  # Model timeout settings
  template_generation_timeout: 60

  # Retry failed AI generation
  ai_retry_attempts: 2

  # Available models
  available_models:
    - "gpt-4o-mini"
    - "gpt-4o"
    - "gpt-3.5-turbo"
    - "gemini-1.5-flash"
    - "gemini-1.5-pro"


# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
#  🚨 ERROR HANDLING & ALERTS
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

error_handling:
  # Continue processing on individual failures
  continue_on_failure: true

  # Save detailed error reports
  save_error_reports: true

  # Email notifications (future feature)
  email_notifications:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    sender_email: ""
    recipient_emails: []

  # Critical error thresholds
  max_consecutive_failures: 5
  failure_rate_threshold: 0.5


# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
#  🔬 DEBUGGING & DEVELOPMENT
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

debug:
  # Enable debug mode
  debug_mode: false

  # Take screenshots on errors
  screenshot_on_error: true

  # Pause between critical operations
  debug_pause_duration: 1.0

  # Save browser console logs
  save_console_logs: false

  # Detailed subprocess logging
  verbose_subprocess_logging: true


# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
#  🎯 PROCESS FILTERING & SELECTION
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

filters:
  # Only process files newer than X days
  max_file_age_days: null

  # Minimum file size in bytes
  min_file_size_bytes: 100

  # Skip files matching patterns
  skip_patterns:
    - "*_backup*"
    - "*_temp*"
    - ".*"

  # Process only specific patterns
  include_patterns: []

  # Process number validation
  validate_process_numbers: true
  min_process_number_length: 20


# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
#  📈 PERFORMANCE & OPTIMIZATION
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

performance:
  # Memory management
  max_memory_usage_mb: 2048

  # Process execution limits
  max_execution_time_minutes: 30

  # Chrome process limits
  max_chrome_instances: 3

  # System resource monitoring
  monitor_system_resources: true

  # Automatic garbage collection
  force_gc_interval: 10


# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
#  💾 STATE MANAGEMENT & PERSISTENCE
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

state:
  # Enable persistent state tracking
  enable_state_persistence: true

  # State file location
  state_file: "Temp/processing_state.json"

  # Save state interval (processes)
  save_state_interval: 5

  # State file backup
  backup_state_files: true
  max_state_backups: 10

  # Recovery options
  auto_resume_on_startup: true
  recovery_prompt: true


# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
#  🎨 USER INTERFACE & EXPERIENCE
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

ui:
  # Progress bar settings
  show_progress_bar: true
  progress_update_interval: 1

  # Console output formatting
  use_colors: true
  show_timestamps: true
  compact_output: false

  # Interactive prompts
  confirm_batch_operations: true
  pause_on_errors: false

  # Status reporting
  show_detailed_stats: true
  realtime_status_updates: true
